on: [push]

jobs:
  create_issues_action:
    runs-on: ubuntu-latest
    name: create issues action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: create issues action
        uses: ./ # Uses an action in the root directory
        # id: hello
        # with: 
        #   who-to-greet: 'Mona the Octocat'
      # - name: Get the output time
      #   run: echo "The time was ${{ steps.hello.outputs.time }}"